services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - patient-service
      - doctor-service
      - appointment-service
      - notification-service
    environment:
      - NODE_ENV=development

  auth-service:
    build:
      context: ./auth-service
      dockerfile: dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development

  patient-service:
    build:
      context: ./patient-service
      dockerfile: dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development

  doctor-service:
    build:
      context: ./doctor-service
      dockerfile: dockerfile
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=development

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: dockerfile
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development

  notification-service:
    build:
      context: ./notification-service
      dockerfile: dockerfile
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=development