name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          dockerfile: ./api-gateway/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
      
      - name: Build and push Auth Service
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          dockerfile: ./auth-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
      
      - name: Build and push Patient Service
        uses: docker/build-push-action@v4
        with:
          context: ./patient-service
          dockerfile: ./patient-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/patient-service:latest
      
      - name: Build and push Doctor Service
        uses: docker/build-push-action@v4
        with:
          context: ./doctor-service
          dockerfile: ./doctor-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/doctor-service:latest
      
      - name: Build and push Appointment Service
        uses: docker/build-push-action@v4
        with:
          context: ./appointment-service
          dockerfile: ./appointment-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/appointment-service:latest
      
      - name: Build and push Notification Service
        uses: docker/build-push-action@v4
        with:
          context: ./notification-service
          dockerfile: ./notification-service/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notification-service:latest